language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer install --dev
  - wget http://www.phing.info/get/phing-latest.phar
  - mv phing-latest.phar phing.phar

script:
  - phing -Ddb.pass='' test
