language: php
php:
  - 5.3
before_script:
  - composer install --dev --no-interaction
  - wget http://www.phing.info/get/phing-latest.phar
  - mv phing-latest.phar phing.phar
  - chmod +x phing.phar

script:
  - phing.phar -Ddb.pass='' test
